services:
  farmbyte-postgresql:
    container_name: farmbyte-postgresql
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
    volumes:
      - ./farmbyte_postgresql/data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - farmbyte-network
    restart: unless-stopped
  farmbyte-api:
    container_name: farmbyte-api
    image: xenonbytesarl/farm-byte-service:latest
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./farmbyte_images/data:/root/farmbyte
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - farmbyte-postgresql
    networks:
      - farmbyte-network
  farmbyte-ui:
    container_name: farmbyte-ui
    image: xenonbytesarl/farm-byte-ui:latest
    environment:
      - UI_PORT=${UI_PORT}
      - VITE_API_BACKEND_URL=${API_BACKEND_URL}
    ports:
      - '${UI_PORT}:80'
    depends_on:
      - farmbyte-api
    networks:
      - farmbyte-network
networks:
  farmbyte-network:
    driver: bridge