services:
  farmbyte-postgresql:
    container_name: farmbyte-postgresql
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - farmbyte_postgresql:/data/postgres
    ports:
      - '5437:${DB_PORT}'
    networks:
      - farmbyte-network
    restart: unless-stopped
  farmbyte-api:
    container_name: farmbyte-api
    image: farmbyte/farmbyte-service:1.0.6
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - farmbyte-postgresql
    networks:
      - farmbyte-network
  farmbyte-ui:
    container_name: farmbyte-ui
    image: farmbyte/farmbyte-portal:1.0.3
    ports:
      - '80:80'
    networks:
      - farmbyte-network
    depends_on:
      - farmbyte-api
networks:
  farmbyte-network:
    driver: bridge

volumes:
  farmbyte_postgresql:
    driver: local