openapi: 3.1.0
info:
  title: Category of Unit of Measure API
  description: |
    REST API endpoints for Category Unit of Measure
  version: 1.0.0
servers:
  - url: http://localhost:8085/api/v1/catalog
    description: Development Server
  - url: http://localhost:8080/api/v1/catalog
    description: Production server
tags:
  - name: UomCategory
    description: "The Uom Category API"

paths:
  /uom-categories:
    post:
      tags:
        - UomCategory
      summary: create a category unit of measure
      operationId: createUomCategory
      security:
        - oAuth:
            - create:uom:category
      requestBody:
        required: true
        description: category uom object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUomCategoryViewRequest'
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUomCategoryViewApiResponse'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        409:
          description: conflict operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    get:
      tags:
        - UomCategory
      operationId: findUomCategories
      summary: find all categories units of measure
      security:
        - oAuth:
            - read:uom:category
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/page.yaml#/page'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/size.yaml#/size'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/attribute.yaml#/attribute'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/direction.yaml#/direction'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindUomCategoriesViewApiResponse'
  /uom-categories/{uomCategoryId}:
    get:
      tags:
        - UomCategory
      summary: find category of unit of measure by id
      operationId: findUomCategoryById
      security:
        - oAuth:
            - read:uom:category
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '#/components/parameters/uomCategoryId'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindUomCategoryByIdViewApiResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    put:
      tags:
        - UomCategory
      summary: update category of unit of measure by id
      operationId: updateUomCategoryById
      security:
        - oAuth:
            - update:uom:category
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '#/components/parameters/uomCategoryId'
      requestBody:
        required: true
        description: category uom object to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUomCategoryViewRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUomCategoryViewApiResponse'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        409:
          description: conflict operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /uom-categories/search:
    get:
      tags:
        - UomCategory
      summary: search category of unit of measure by a keyword
      operationId: searchUomCategory
      security:
        - oAuth:
            - read:uom:category
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/page.yaml#/page'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/size.yaml#/size'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/attribute.yaml#/attribute'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/direction.yaml#/direction'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/keyword.yaml#/keyword'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUomCategoriesViewApiResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

components:
  parameters:
    uomCategoryId:
      in: path
      name: uomCategoryId
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    ApiErrorResponse:
      $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-error-response.yaml#/ApiErrorResponse'
    CreateUomCategoryViewRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        parentUomCategoryId:
          type: string
          format: uuid
    UomCategoryView:
      type: object
      required:
        - id
        - name
        - active
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        parentUomCategoryId:
          type: string
          format: uuid
        active:
          type: boolean
    UomCategoryViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryView'
    CreateUomCategoryViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    CreateUomCategoryViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/CreateUomCategoryViewResponse'
    FindUomCategoryByIdViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    FindUomCategoryByIdViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/FindUomCategoryByIdViewResponse'
    FindUomCategoriesViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    FindUomCategoriesPageInfoViewResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/page-info-view-response.yaml#/PageInfoViewResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/FindUomCategoriesViewResponse'
    FindUomCategoriesViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/FindUomCategoriesPageInfoViewResponse'
    SearchUomCategoriesViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    SearchUomCategoriesPageInfoViewResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/page-info-view-response.yaml#/PageInfoViewResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/SearchUomCategoriesViewResponse'
    SearchUomCategoriesViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/SearchUomCategoriesPageInfoViewResponse'
    UpdateUomCategoryViewRequest:
      allOf:
        - $ref: '#/components/schemas/UomCategoryView'
    UpdateUomCategoryViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryView'
    UpdateUomCategoryViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/UpdateUomCategoryViewResponse'