openapi: 3.1.0
info:
  title: Category of Unit of Measure API
  description: |
    REST API endpoints for Category Unit of Measure
  version: 1.0.0
servers:
  - url: http://localhost:8085/api/v1/catalog
    description: Development Server
  - url: http://localhost:8080/api/v1/catalog
    description: Production server
tags:
  - name: UomCategory
    description: "The Uom Category API"

paths:
  /uom-categories:
    post:
      tags:
        - UomCategory
      summary: create a category unit of measure
      operationId: createUomCategory
      security:
        - oAuth:
            - create:uom:category
      requestBody:
        required: true
        description: category uom object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUomCategoryViewRequest'
      parameters:
        - $ref: '#/components/parameters/accept-language'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUomCategoryViewApiResponse'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        409:
          description: conflict operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    get:
      tags:
        - UomCategory
      operationId: findUomCategories
      security:
        - oAuth:
            - read:uom:category
      parameters:
        - $ref: '#/components/parameters/accept-language'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/attribute'
        - $ref: '#/components/parameters/direction'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindUomCategoriesViewApiResponse'
  /uom-categories/{uomCategoryId}:
    get:
      tags:
        - UomCategory
      summary: find category of unit of measure by id
      operationId: findUomCategoryById
      security:
        - oAuth:
            - read:uom:category
      parameters:
        - $ref: '#/components/parameters/accept-language'
        - $ref: '#/components/parameters/uomCategoryId'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindUomCategoryByIdViewApiResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /uom-categories/search:
    get:
      tags:
        - UomCategory
      summary: search category of unit of measure by a keyword
      operationId: searchUomCategory
      security:
        - oAuth:
            - read:uom:category
      parameters:
        - $ref: '#/components/parameters/accept-language'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/attribute'
        - $ref: '#/components/parameters/direction'
        - $ref: '#/components/parameters/keyword'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUomCategoriesViewApiResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

components:
  parameters:
    accept-language:
      name: Accept-Language
      in: header
      required: true
      schema:
        type: string
        enum: [en, fr]
    uomCategoryId:
      in: path
      name: uomCategoryId
      required: true
      schema:
        type: string
        format: uuid
    page:
      in: path
      name: page
      required: true
      schema:
        type: integer
        format: int32
    size:
      in: path
      name: size
      required: true
      schema:
        type: integer
        format: int32
    attribute:
      in: path
      name: attribute
      required: true
      schema:
        type: string
    direction:
      in: path
      name: direction
      required: true
      schema:
        type: string
        enum: [ASC, DSC]
    keyword:
      in: path
      name: keyword
      required: true
      schema:
        type: string
  schemas:
    ValidationError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
        message:
          type: string
    ApiResponse:
      type: object
      required:
        - timestamp
        - code
        - status
        - success
      properties:
        timestamp:
          type: string
        code:
          type: integer
          format: int32
        status:
          type: string
        success:
          type: boolean
    ApiSuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            message:
              type: string
    ApiErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          required:
            - reason
            - path
            - trackId
          properties:
            reason:
              type: string
            developerMessage:
              type: string
            path:
              type: string
            trackId:
              type: string
              format: uuid
            error:
              type: array
              items:
                $ref: '#/components/schemas/ValidationError'
    CreateUomCategoryViewRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        parentUomCategoryId:
          type: string
          format: uuid
    UomCategoryViewResponse:
      type: object
      required:
        - id
        - name
        - parenUomCategoryId
        - active
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        parentUomCategoryId:
          type: string
          format: uuid
        active:
          type: boolean
    CreateUomCategoryViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    CreateUomCategoryViewApiResponse:
      allOf:
        - $ref: '#/components/schemas/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/CreateUomCategoryViewResponse'
    FindUomCategoryByIdViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    FindUomCategoryByIdViewApiResponse:
      allOf:
        - $ref: '#/components/schemas/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/FindUomCategoryByIdViewResponse'
    PageInfoViewResponse:
      type: object
      required:
        - first
        - last
        - pageSize
        - totalElement
        - totalPages
      properties:
        first:
          type: boolean
        last:
          type: boolean
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
    FindUomCategoriesViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    FindUomCategoriesPageInfoViewResponse:
      allOf:
        - $ref: '#/components/schemas/PageInfoViewResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/FindUomCategoriesViewResponse'
    FindUomCategoriesViewApiResponse:
      allOf:
        - $ref: '#/components/schemas/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                type: array
                items:
                  $ref: '#/components/schemas/FindUomCategoriesPageInfoViewResponse'
    SearchUomCategoriesViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomCategoryViewResponse'
    SearchUomCategoriesPageInfoViewResponse:
      allOf:
        - $ref: '#/components/schemas/PageInfoViewResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/SearchUomCategoriesViewResponse'
    SearchUomCategoriesViewApiResponse:
      allOf:
        - $ref: '#/components/schemas/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                type: array
                items:
                  $ref: '#/components/schemas/SearchUomCategoriesPageInfoViewResponse'