openapi: 3.1.0
info:
  title: Category of Unit of Measure API
  description: |
    REST API endpoints for Category Unit of Measure
  version: 1.0.0
servers:
  - url: http://localhost:8085/api/v1/catalog
    description: Development Server
  - url: http://localhost:8080/api/v1/catalog
    description: Production server
tags:
  - name: UomCategory
    description: "The Uom Category API"

paths:
  /uom-categories:
    post:
      tags:
        - UomCategory
      summary: create a category unit of measure
      operationId: createUomCategory
      security:
        - oAuth:
            - create:uom:category
      requestBody:
        required: true
        description: category uom object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUomCategoryViewRequest'
      parameters:
        - $ref: '#/components/parameters/accept-language'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponse'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        409:
          description: conflict operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  parameters:
    accept-language:
      name: Accept-Language
      in: header
      required: true
      schema:
        type: string
        enum: [en, fr]
  schemas:
    ValidationError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
        message:
          type: string
    ApiResponse:
      type: object
      required:
        - timestamp
        - code
        - status
        - success
      properties:
        timestamp:
          type: string
        code:
          type: integer
          format: int32
        status:
          type: string
        success:
          type: boolean
    ApiSuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            message:
              type: string
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/CreateUomCategoryViewResponse'
    ApiErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          required:
            - reason
            - path
            - trackId
          properties:
            reason:
              type: string
            developerMessage:
              type: string
            path:
              type: string
            trackId:
              type: string
              format: uuid
            error:
              type: array
              items:
                $ref: '#/components/schemas/ValidationError'
    CreateUomCategoryViewRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        parentUomCategoryId:
          type: string
          format: uuid
    CreateUomCategoryViewResponse:
      type: object
      required:
        - id
        - name
        - parenUomCategoryId
        - active
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        parentUomCategoryId:
          type: string
          format: uuid
        active:
          type: boolean