openapi: 3.1.0
info:
  title: Unit of Measure API
  description: |
    REST API endpoints for Unit of Measure
  version: 1.0.0
servers:
  - url: http://localhost:8085/api/v1/catalog
    description: Development Server
  - url: http://localhost:8080/api/v1/catalog
    description: Production server
tags:
  - name: Uom
    description: "The Uom API"

paths:
  /uoms:
    post:
      tags:
        - Uom
      summary: create an unit of measure
      operationId: createUom
      security:
        - oAuth:
            - create:uom
      requestBody:
        required: true
        description: uom object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUomViewRequest'
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUomViewApiResponse'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        409:
          description: conflict operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    get:
      tags:
        - Uom
      operationId: findUoms
      security:
        - oAuth:
            - read:uom
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/page.yaml#/page'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/size.yaml#/size'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/attribute.yaml#/attribute'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/direction.yaml#/direction'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindUomsViewApiResponse'
  /uoms/{uomId}:
    get:
      tags:
        - Uom
      summary: find unit of measure by id
      operationId: findUomById
      security:
        - oAuth:
            - read:uom
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '#/components/parameters/uomId'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindUomByIdViewApiResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  /uoms/search:
    get:
      tags:
        - Uom
      summary: search unit of measure by a keyword
      operationId: searchUom
      security:
        - oAuth:
            - read:uom
      parameters:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/accept-language.yaml#/accept-language'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/page.yaml#/page'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/size.yaml#/size'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/attribute.yaml#/attribute'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/direction.yaml#/direction'
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/parameters/keyword.yaml#/keyword'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUomsViewApiResponse'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  parameters:
    uomId:
      in: path
      name: uomId
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    ApiErrorResponse:
      $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-error-response.yaml#/ApiErrorResponse'
    CreateUomViewRequest:
      type: object
      required:
        - name
        - uomCategoryId
        - uomType
      properties:
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        uomCategoryId:
          type: string
          format: uuid
        uomType:
          type: string
          enum:
            - LOWER
            - REFERENCE
            - GREATER
        ratio:
          type: number
          format: double
    UomViewResponse:
      type: object
      required:
        - id
        - name
        - uomCategoryId
        - uomType
        - ratio
        - active
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        uomCategoryId:
          type: string
          format: uuid
        uomType:
          type: string
          enum:
            - LOWER
            - REFERENCE
            - GREATER
        ratio:
          type: number
          format: double
        active:
          type: boolean
    CreateUomViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomViewResponse'
    CreateUomViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/CreateUomViewResponse'
    FindUomByIdViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomViewResponse'
    FindUomByIdViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/FindUomByIdViewResponse'
    FindUomsViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomViewResponse'
    FindUomsPageInfoViewResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/page-info-view-response.yaml#/PageInfoViewResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/FindUomsViewResponse'
    FindUomsViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/FindUomsPageInfoViewResponse'
    SearchUomsViewResponse:
      allOf:
        - $ref: '#/components/schemas/UomViewResponse'
    SearchUomsPageInfoViewResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/page-info-view-response.yaml#/PageInfoViewResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/SearchUomsViewResponse'
    SearchUomsViewApiResponse:
      allOf:
        - $ref: '../../../../../../../common/common-resource/src/main/resources/openapi/schemas/api-success-response.yaml#/ApiSuccessResponse'
        - type: object
          properties:
            data:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/SearchUomsPageInfoViewResponse'

