name: CIPipelineFarmByteUI
on:
  workflow_dispatch:
    inputs:
      Build:
        default: false
        description: Build docker image
        type: boolean
        required: false
jobs:
  build-image:
    runs-on: self-hosted
    name: Build docker image
    if: ${{ github.event.inputs.Build }}
    steps:
      - name: Build the Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          cd farm-byte-ui
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date in number
        id: current_date
        run: |
          echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Build image and push to docker registry
        uses: docker/build-push-action@v5
        with:
          context: farm-byte-ui
          file: docker/ui/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/farm-byte-ui:${{ steps.extract_version.outputs.VERSION }}.${{ steps.current_date.outputs.CURRENT_DATE }}, ${{ secrets.DOCKERHUB_USERNAME }}/farm-byte-ui:latest
          build-args: |
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
            PROFILE=${{ github.event.inputs.Environment }}