name: CDPipelineFarmByte
on:
  workflow_dispatch:
    inputs:
      Environment:
        default: ""
        description: Choose target environment
        type: choice
        options:
          - int
          - rct
          - prod
        required: true
      Image:
        default: ""
        description: Image name
        type: string
        required: false
      Tag:
        default: ""
        description: Version of image
        type: string
        required: false
jobs:
  deploy-service:
    name: Deploy FarmByte UI
    runs-on: self-hosted
    steps:
      - name: Create deployment folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: mkdir -p farmbyte
          overwrite: true
      - name: Copy docker compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          overwrite: true
          source: docker-compose.yml
          target: farmbyte
      - name: Set environment variables and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            export DB_SERVER=${{ secrets.DB_SERVER }}
            export ACTIVE_PROFILE=${{ github.event.inputs.Environment }}
            if [ ${{github.event.inputs.Environment}} == 'rct' ]; then
              export DB_USER=${{ secrets.DB_USER_RCT }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD_RCT }}
              export DB_PORT=${{ secrets.DB_PORT_RCT }}
              export APP_PORT=${{ secrets.APP_PORT_RCT }}
              export DB_NAME=${{ secrets.DB_NAME_RCT }}
              export VITE_API_BACKEND_URL=${{ secrets.VITE_API_BACKEND_URL_RCT }}
              export UI_PORT=${{ secrets.UI_PORT_RCT }}
            elif [ ${{github.event.inputs.Environment}} == 'prod' ]; then
              export DB_USER=${{ secrets.DB_USER_PROD }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }}
              export DB_PORT=${{ secrets.DB_PORT_PROD }}
              export APP_PORT=${{ secrets.APP_PORT_PROD }}
              export DB_NAME=${{ secrets.DB_NAME_PROD }}
              export VITE_API_BACKEND_URL=${{ secrets.VITE_API_BACKEND_URL_PROD }}
              export UI_PORT=${{ secrets.UI_PORT_PROD }}
            else 
              export DB_USER=${{ secrets.DB_USER_INT }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD_INT }}
              export DB_PORT=${{ secrets.DB_PORT_INT }}
              export APP_PORT=${{ secrets.APP_PORT_INT }}
              export DB_NAME=${{ secrets.DB_NAME_INT }}
              export VITE_API_BACKEND_URL=${{ secrets.VITE_API_BACKEND_URL_INT }}
              export UI_PORT=${{ secrets.UI_PORT_INT }}
            fi
            cd farmbyte
            docker compose -f docker-compose.yml pull -q
            docker compose down
            docker compose -f docker-compose.yml up -d